apiVersion: v1
description: Helm chart for deployment generic app on Kubernetes
icon: https://helm.b3o.io/charts/generic-app/icon.png
maintainers:
- name: Bruno Correia
  email: brunogomescorreia@gmail.com
name: generic-app
version: v0.1.5
kubeVersion: ">= 1.19.0-0"
home: https://helm.b3o.io
keywords:
  - generic
  - application
sources:
  - https://github.com/b3outputs/helm-charts
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: deployment adjustments
    - kind: added
      description: Documentation detail
    - kind: fixed
      description: Variables in ingress file
  artifacthub.io/containsSecurityUpdates: "true"